### PR TITLE
To rotate not Filename but Directory

### PR DESCRIPTION
**Pull request by masartz**
Hi.

Actually, my product running by Apache.
Those log files rotate file path hourly( like below)

> CustomLog "|/usr/sbin/cronolog /var/log/httpd/%Y/%m/%d/%H/access_log"

So I would like to output as same format in Plack::MIddleware::Accesslog + File::RotateLogs 
Would you review this PR?

### CODE REVIEW

**Comment by masartz** [comment]
ping @kazeburo -san ...

**Comment by kazeburo** [comment]
Not required removing directory?

**Comment by masartz** [comment]
@kazeburo 

oh.. I see.

I thought that maxage option is set as undefined in my purpose case.
And then I will delete files by other tool( maybe tmpwatch).

Even files are deleted by other tool, I think that I could not delete directory by this module.

But, It means this PR will disable maxage option any time. Sounds terrible... 

Making some wrapper module is better..?

**Comment by kazeburo** [comment]
Just released 0.08!
Thank you

**Comment by masartz** [comment]
Thank you for Reviewing & Merging!
I will use it.

**Pull request merged**
